apiVersion: v1
kind: Pod
metadata:
  name: spring-dockerize-default-pod
spec:
  containers:
  - name: spring-dockerize-default-pod
    image: spring-boot-dockerized:0.0.1-SNAPSHOT
    # resources:
      # requests:
      #   memory: "64Mi"
      # limits:
      #   memory: "128Mi"  

